name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: npm install

      - name: Copy utils
        run: ./scripts/build.sh

      - name: Lint
        run: npm run lint

      - name: Typecheck
        run: npm run tsc

      - name: Build
        run: npm run build:ci
